Repository opensearch-project/cross-cluster-replication, pull requests merged in 2022-06, with the labels that each got.

#415 [Backport 1.2 ]Sync the mapping from leader index and retry for MapperParsingExcepti…
  src/main/kotlin/org/opensearch/replication/action/replay/TransportReplayChangesAction.kt
  src/test/kotlin/org/opensearch/replication/task/shard/TransportReplayChangesActionIT.kt
Labels: backport 1.1

#416 Modified _stop replication API to remove any stale replication settings on existing index
  src/main/kotlin/org/opensearch/replication/action/stop/TransportStopIndexReplicationAction.kt
  src/test/kotlin/org/opensearch/replication/MultiClusterRestTestCase.kt
  src/test/kotlin/org/opensearch/replication/integ/rest/StopReplicationIT.kt
Labels: backport 1.1, backport 1.2

#419 Validate leader index primary shard state before starting replication (#407)
  src/main/kotlin/org/opensearch/replication/action/index/TransportReplicateIndexAction.kt
  src/main/kotlin/org/opensearch/replication/util/ValidationUtil.kt
  src/test/kotlin/org/opensearch/replication/integ/rest/StartReplicationIT.kt
Labels: backport 1.1, backport 1.2, backport 1.3

#423 Sync the mapping from leader index and retry for MapperParsingExcepti…
  src/main/kotlin/org/opensearch/replication/action/replay/TransportReplayChangesAction.kt
  src/test/kotlin/org/opensearch/replication/task/shard/TransportReplayChangesActionIT.kt
Labels: backport 1.1

#420 Added error logs for replication state transition to auto_pause or failed state with reason (#408)
  src/main/kotlin/org/opensearch/replication/task/index/IndexReplicationTask.kt
Labels: backport 1.1, backport 1.2, backport 1.3

#434 Add custom build.sh to publish the plugin zip
  scripts/build.sh
Labels: backport 2.1
