Repository opensearch-project/cross-cluster-replication, pull requests merged in 2022-07, with the labels that each got.

#438 Fixing the follower checkpoint updation in follower stats API
  src/main/kotlin/org/opensearch/replication/task/shard/ShardReplicationTask.kt
  src/main/kotlin/org/opensearch/replication/task/shard/TranslogSequencer.kt
  src/test/kotlin/org/opensearch/replication/integ/rest/StartReplicationIT.kt
  src/test/kotlin/org/opensearch/replication/task/shard/TranslogSequencerTests.kt
Labels: backport 1.1, backport 1.2, backport 2.0, backport 1.3, backport 2.1

#455 Use the published zip for security plugin
  .github/workflows/security-tests.yml
  build.gradle
Labels: backport 2.1, backport 2.x

#450 Incremented version to 2.1.1.
  build.gradle
Labels: v2.1.1

#449 Staging for version increment automation
  build.gradle
Labels: backport 2.1
