Repository opensearch-project/cross-cluster-replication, pull requests merged in 2022-10, with the labels that each got.

#573 Upgrade Snakeyml and Jackson
  build.gradle
Labels: backport 1.1, backport 1.2, backport 2.0, backport 1.3, backport 2.1, backport 2.x, backport 2.2

#568 added groupId to pluginzip publication
  build.gradle
Labels: backport 2.x

#589 add groupId = org.opensearch.plugin
  build.gradle
Labels: backport 2.x, v2.4.0

#596 Updated jackson databind version to 2.13.4.2
  build.gradle
Labels: backport 2.x, backport 1.x

#591 Add support for windows & mac build
  .github/workflows/build-and-test.yml
  .github/workflows/build.yml
Labels: backport 2.x

#601 Include default index settings during leader setting validation
  src/main/kotlin/org/opensearch/replication/action/index/TransportReplicateIndexAction.kt
Labels: backport 1.1, backport 1.2, backport 2.0, backport 1.3, backport 2.1, backport 2.x, backport 2.2, backport 1.x, backport 2.3

#607 [Backport 1.x]Changed jackson databind version to 2.13.4.2 and backported to 1.x
  build.gradle
  src/main/kotlin/org/opensearch/replication/task/CrossClusterReplicationTask.kt
Labels: backport 1.x

#609 [Backport] Include default index settings during leader setting validation (#601)
  src/main/kotlin/org/opensearch/replication/action/index/TransportReplicateIndexAction.kt
Labels: backport 1.1, backport 1.2, backport 2.0, backport 1.3, backport 2.1

#608 Changed version of jackson databind to 2.13.4.2 for OS 1.3
  build.gradle
Labels: backport 1.3

#617 Add 2.4 release notes
  release-notes/opensearch-cross-cluster-replication.release-notes-2.4.0.0.md
Labels: backport 2.4
