Repository opensearch-project/cross-cluster-replication, pull requests merged in 2022-08, with the labels that each got.

#461 Adding Index Settings validation before starting replication
  src/main/kotlin/org/opensearch/replication/action/index/TransportReplicateIndexAction.kt
  src/main/kotlin/org/opensearch/replication/util/ValidationUtil.kt
  src/test/kotlin/org/opensearch/replication/integ/rest/StartReplicationIT.kt
Labels: backport 2.x

#469 Changes to support replication plugin on OpenSearch v2.2.0
  .github/workflows/security-tests.yml
  build.gradle
  src/main/kotlin/org/opensearch/replication/metadata/TransportUpdateMetadataAction.kt
Labels: backport 2.x

#474 Modified security artifacts to fetch from latest build version
  build.gradle
Labels: backport 2.x, backport 2.2

#477 Added release notes for v2.2.0 release
  release-notes/opensearch-cross-cluster-replication.release-notes-2.2.0.0.md
Labels: backport 2.2

#491 Updating filters as well during Alias update
  src/main/kotlin/org/opensearch/replication/task/index/IndexReplicationTask.kt
  src/test/kotlin/org/opensearch/replication/integ/rest/StartReplicationIT.kt
Labels: v2.x

#410 Modified _stop replication API to remove any stale replication settings on existing index
  src/main/kotlin/org/opensearch/replication/action/stop/TransportStopIndexReplicationAction.kt
  src/test/kotlin/org/opensearch/replication/MultiClusterRestTestCase.kt
  src/test/kotlin/org/opensearch/replication/integ/rest/StopReplicationIT.kt
Labels: backport 2.0, backport 2.1, backport 2.x, backport 2.2

#508 Add lastExecutionTime for autofollow coroutine
  src/main/kotlin/org/opensearch/replication/task/autofollow/AutoFollowTask.kt
  src/test/kotlin/org/opensearch/replication/integ/rest/UpdateAutoFollowPatternIT.kt
Labels: backport 1.1, backport 1.2, backport 2.0, backport 1.3, backport 2.1, backport 2.x, backport 2.2

#497 Fix for missing ShardReplicationTasks on new nodes
  src/main/kotlin/org/opensearch/replication/task/index/IndexReplicationTask.kt
  src/test/kotlin/org/opensearch/replication/task/index/IndexReplicationTaskTests.kt
Labels: backport 1.1, backport 1.2, backport 2.0, backport 1.3, backport 2.1, backport 2.x, backport 2.2

#486 For segrep enabled indices, use NRTReplicationEngine for replica shards
  src/main/kotlin/org/opensearch/replication/ReplicationPlugin.kt
Labels: backport 2.x
