Repository opensearch-project/cross-cluster-replication, pull requests merged in 2023-06, with the labels that each got.

#937 Handling exception in getAssignment method
  src/main/kotlin/org/opensearch/replication/task/shard/ShardReplicationExecutor.kt
  src/test/kotlin/org/opensearch/replication/task/shard/ShardReplicationExecutorTests.kt
Labels: backport 1.1, backport 1.2, backport 1.3, backport 1.x, backport 2.3

#897 [Backport] Modify autofollow retry scheduler logic check to account for completed runs (#839)
  src/main/kotlin/org/opensearch/replication/task/autofollow/AutoFollowTask.kt
  src/test/kotlin/org/opensearch/replication/integ/rest/UpdateAutoFollowPatternIT.kt
Labels: backport 1.1, backport 1.2, backport 2.0, backport 1.3, backport 2.1, backport 2.x, backport 1.x, backport 2.3, backport 2.5, backport 2.7, backport 2.8

#951 [Backport] Initialize the leaderCheckpoint with follower shard's localCheckpoint…
  src/main/kotlin/org/opensearch/replication/repository/RemoteClusterRestoreLeaderService.kt
  src/main/kotlin/org/opensearch/replication/seqno/RemoteClusterRetentionLeaseHelper.kt
  src/main/kotlin/org/opensearch/replication/task/index/IndexReplicationTask.kt
  src/main/kotlin/org/opensearch/replication/task/shard/ShardReplicationTask.kt
  src/test/kotlin/org/opensearch/replication/MultiClusterRestTestCase.kt
  src/test/kotlin/org/opensearch/replication/integ/rest/ReplicationStopThenRestartIT.kt
Labels: backport 1.1, backport 1.2

#905 Remove any stale replication tasks from cluster state
  src/main/kotlin/org/opensearch/replication/action/stop/TransportStopIndexReplicationAction.kt
Labels: backport 1.1, backport 1.2, backport 2.0, backport 1.3, backport 2.1, backport 2.x, backport 2.2, backport es_7.10, backport 1.x, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8
