Repository opensearch-project/cross-cluster-replication, pull requests merged in 2023-05, with the labels that each got.

#826 Extract number of nodes
  scripts/integtest.sh
Labels: backport 2.x, backport 2.7

#834 Update to set remoteTranslogEnabled=false
  src/test/kotlin/org/opensearch/index/translog/ReplicationTranslogDeletionPolicyTests.kt
Labels: backport 2.x

#833 Add retention lease with followerClusterUUID
  src/main/kotlin/org/opensearch/replication/action/resume/TransportResumeIndexReplicationAction.kt
  src/main/kotlin/org/opensearch/replication/action/stop/TransportStopIndexReplicationAction.kt
  src/main/kotlin/org/opensearch/replication/repository/RemoteClusterRepository.kt
  src/main/kotlin/org/opensearch/replication/seqno/RemoteClusterRetentionLeaseHelper.kt
  src/main/kotlin/org/opensearch/replication/task/index/IndexReplicationTask.kt
  src/main/kotlin/org/opensearch/replication/task/shard/ShardReplicationTask.kt
  src/test/kotlin/org/opensearch/replication/bwc/BackwardsCompatibilityIT.kt
Labels: backport 1.1, backport 1.2, backport 2.0, backport 1.3, backport 2.1, backport 2.x, backport 2.2, backport 1.x, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7

#866 [Bug] Handle serialization issues with UpdateReplicationStateDetailsRequest
  src/main/kotlin/org/opensearch/replication/action/replicationstatedetails/UpdateReplicationStateDetailsRequest.kt
  src/test/kotlin/org/opensearch/replication/action/replicationstatedetails/UpdateReplicationStateDetailsRequestTests.kt
Labels: backport 1.1, backport 1.2, backport 2.0, backport 1.3, backport 2.1, backport 2.x, backport 2.2, backport 1.x, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7

#888 Merge pull request #624 from priyatsh/main
  src/main/kotlin/org/opensearch/replication/task/index/IndexReplicationTask.kt
  src/test/kotlin/org/opensearch/replication/integ/rest/StartReplicationIT.kt
Labels: backport 1.1, backport 1.2, backport 1.3, backport 1.x, backport 2.3, backport 2.5, backport 2.7

#839 Modify autofollow retry scheduler logic to account for completed runs
  src/main/kotlin/org/opensearch/replication/task/autofollow/AutoFollowTask.kt
  src/test/kotlin/org/opensearch/replication/integ/rest/UpdateAutoFollowPatternIT.kt
Labels: backport 1.1, backport 1.2, backport 2.0, backport 1.3, backport 2.1, backport 2.x, backport 2.2, backport es_7.10, backport 1.x, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7

#910 [Backport] Modified autofollow stats to rely on single source for failed indices (#708)
  src/main/kotlin/org/opensearch/replication/ReplicationPlugin.kt
  src/main/kotlin/org/opensearch/replication/task/autofollow/AutoFollowTask.kt
  src/test/kotlin/org/opensearch/replication/ReplicationHelpers.kt
  src/test/kotlin/org/opensearch/replication/integ/rest/UpdateAutoFollowPatternIT.kt
Labels: backport 1.1, backport 1.2, backport 1.3

#909 [Backport] Handle clean-up of stale index task during cancellation (#645)
  src/main/kotlin/org/opensearch/replication/task/index/IndexReplicationTask.kt
  src/test/kotlin/org/opensearch/replication/ReplicationHelpers.kt
  src/test/kotlin/org/opensearch/replication/task/index/IndexReplicationTaskTests.kt
Labels: backport 1.1, backport 1.2, backport 1.3, backport 2.3, backport 2.5, backport 2.7, backport 2.8

#881 Handling exception in getAssignment method
  src/main/kotlin/org/opensearch/replication/task/shard/ShardReplicationExecutor.kt
  src/test/kotlin/org/opensearch/replication/task/shard/ShardReplicationExecutorTests.kt
Labels: backport 1.1, backport 1.2, backport 1.3, backport 2.x, backport 1.x, backport 2.3, backport 2.5, backport 2.7, backport 2.8
