Repository opensearch-project/cross-cluster-replication, pull requests merged in 2023-04, with the labels that each got.

#772 Handled batch requests for replication metadata update under cluster state
  src/main/kotlin/org/opensearch/replication/metadata/UpdateReplicationMetadata.kt
  src/test/kotlin/org/opensearch/replication/metadata/state/UpdateReplicationMetadataTests.kt
Labels: backport 1.1, backport 1.2, backport 2.0, backport 1.3, backport 2.1, backport 2.x, backport 2.2, backport 1.x, backport 2.3, backport 2.4, backport 2.5, backport 2.6

#757 handling null pointer exception in multi-filed mapping
  src/main/kotlin/org/opensearch/replication/task/index/IndexReplicationTask.kt
Labels: backport 2.0, backport 2.1, backport 2.x, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6

#786 Adding a proxy mode connection setup for CCR
  src/main/kotlin/org/opensearch/replication/repository/RemoteClusterRepositoriesService.kt
  src/test/kotlin/org/opensearch/replication/repository/RemoteClusterRepositoriesServiceTests.kt
Labels: backport 2.x

#799 Add release notes for v2.7.0
  release-notes/opensearch-cross-cluster-replication.release-notes-2.7.0.0.md
Labels: backport 2.7

#802 Add setting to use document replication for system indices.
  src/main/kotlin/org/opensearch/replication/metadata/store/ReplicationMetadataStore.kt
Labels: backport 2.x

#760 Allow knn index to be used with ccr
  .github/workflows/security-knn-tests.yml
  .github/workflows/security-tests.yml
  build.gradle
  src/main/kotlin/org/opensearch/replication/ReplicationPlugin.kt
  src/main/kotlin/org/opensearch/replication/action/index/TransportReplicateIndexAction.kt
  src/main/kotlin/org/opensearch/replication/action/resume/TransportResumeIndexReplicationAction.kt
  src/main/kotlin/org/opensearch/replication/util/ValidationUtil.kt
  src/test/kotlin/org/opensearch/replication/BasicReplicationIT.kt
  src/test/kotlin/org/opensearch/replication/MultiClusterRestTestCase.kt
Labels: backport 2.7
