Repository opensearch-project/cross-cluster-replication, pull requests merged in 2024-01, with the labels that each got.

#1302 Use latest version of ipaddress Library
  build.gradle
Labels: backport 2.x

#1304 Ignoring update of final type settings in updateSettings function
  src/main/kotlin/org/opensearch/replication/task/index/IndexReplicationTask.kt
Labels: backport 2.x, backport 2.11

#1298 Remove references to admin:admin
  HANDBOOK.md
  build.gradle
  scripts/integtest.sh
Labels: backport 2.x, v2.12.0
