Repository opensearch-project/cross-cluster-replication, pull requests merged in 2024-02, with the labels that each got.

#1315 Fix build failures
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: backport 2.x

#1321 Create opensearch-cross-cluster-replication.release-notes-2.12.0.0.md
  release-notes/opensearch-cross-cluster-replication.release-notes-2.12.0.0.md
Labels: backport 2.x, backport 2.12

#1329 Updates 2.12.0 release notes
  build.gradle
  release-notes/opensearch-cross-cluster-replication.release-notes-2.12.0.0.md
Labels: backport 2.x, v2.12.0, backport 2.12

#1331 Fixes base64 encoded hardcoded admin credentials
  build.gradle
  src/test/kotlin/org/opensearch/replication/MultiClusterRestTestCase.kt
Labels: backport 2.x, v2.12.0, backport 2.12
